name: Pake Auto Build
on:
  workflow_dispatch:
    inputs:
      url:
        description: '目标网站URL'
        required: true
      app_name:
        description: '应用名称（支持中文）'
        required: true
      icon_url:
        description: '图标URL（可选）'
        required: false

jobs:
  build-exe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # 强制使用v4版本[4](@ref)[5](@ref)
    
    - name: 设置Node环境
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: 安装Pake
      run: npm install pake-cli -g

    - name: 设置默认图标
      run: |
        DEFAULT_ICON="https://example.com/blue-whale.png"  # 替换为实际默认图标URL
        echo "ICON_URL=${ICON_URL:-$DEFAULT_ICON}" >> $GITHUB_ENV

    - name: 执行打包
      run: |
        pake ${{ inputs.url }} \
          --name "${{ inputs.app_name }}" \
          --icon ${{ env.ICON_URL }} \
          --transparent
        
    - name: 上传产物
      uses: actions/upload-artifact@v4
      with:
        name: pake-build
        path: ./${{ inputs.app_name }}.exe
