name: Package Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build website
      run: npm run build # Assuming you have a build script in your package.json

    - name: Copy built files to electron app directory
      run: cp -r dist/* electron-app/

    - name: Install Electron Builder
      run: npm install --save-dev electron-builder

    - name: Configure Electron Builder
      run: |
        echo '{"productName": "MyWebsite", "appId": "com.example.mywebsite", "directories": {"output": "release"}, "files": ["**"], "win": {"target": "nsis"}, "android": {"target": "apk"}}' > electron-app/builder-config.json

    - name: Build Windows EXE
      working-directory: ./electron-app
      run: npx electron-builder --config builder-config.json --win nsis

    - name: Build Android APK
      working-directory: ./electron-app
      run: npx electron-builder --config builder-config.json --android apk

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-website-packages
        path: ./electron-app/release/



