name: PAKE 自动构建
on:
  workflow_dispatch:
    inputs:
      url:
        description: '网站URL（必须包含https://前缀）'
        required: true
      app_name:
        description: '应用中文名称（支持直接输入中文）'
        required: true
      icon_url:
        description: '自定义图标URL（可选）'
        required: false

jobs:
  build-executable:
    runs-on: windows-latest  # 显式指定Windows构建环境
    steps:
    - uses: actions/checkout@v4

    - name: 配置Node环境
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: 设置镜像源
      run: npm config set registry https://registry.npmmirror.com

    - name: 安装Pake CLI
      run: npm install pake-cli@latest -g

    - name: 设置图标参数
      run: |
        DEFAULT_ICON="https://s3.ax1x.com/2021/03/09/6Id9OO.png"  # 蓝色鲸鱼默认图标
        ICON_FLAG=$([ -z "${{ inputs.icon_url }}" ] && echo "$DEFAULT_ICON" || echo "${{ inputs.icon_url }}")
        echo "ICON=$ICON_FLAG" >> $GITHUB_ENV

    - name: 执行打包
      run: |
        pake "${{ inputs.url }}" \
          --name "${{ inputs.app_name }}" \
          --icon "${{ env.ICON }}" \
          --width 1200 \
          --height 800

    - name: 自动重命名
      run: mv "${{ inputs.app_name }}.exe" "${${{ inputs.app_name }}// /_}.exe"  # 处理空格问题

    - name: 上传制品
      uses: actions/upload-artifact@v3
      with:
        name: pake-output
        path: ./${{ inputs.app_name }}*.exe
