name: Pake Build

on:
  workflow_dispatch:
    inputs:
      url:
        description: '要封装的网站URL'
        required: true
      app_name:
        description: '应用名称（支持中文）'
        required: true
      icon_base64:
        description: '图标的base64编码'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Pake
      run: npm install -g pake-cli

    - name: Create Pake configuration
      run: |
        echo "{
          \"url\": \"${{ github.event.inputs.url }}\",
          \"name\": \"${{ github.event.inputs.app_name }}\",
          \"icon\": \"${{ github.event.inputs.icon_base64 }}\"
        }" > pake-config.json

    - name: Build Pake application
      run: pake build --config pake-config.json

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pake-app
        path: dist/
